### ISSUE TITLE
imagine dead issues

### ISSUE THREAD

**Issue by SomeoneRand0m101** [overlisted/reactor-plugin#1]
damn imagine doing this in a 1000 year old video
and also using this plugin (funny)
plugin is such a good plugin totally

**Comment by overlisted** [comment]
very cool

**Comment by overlisted** [comment]
did you change the config file? that's where the options for /makeshield are

**Comment by SomeoneRand0m101** [comment]
Damn im suprised you still respond to this, Also I didnt and thanks for that let me edit that real quick

**Comment by overlisted** [comment]
yes if you use a server jar that supports mods and plugins at the same time

**Comment by SomeoneRand0m101** [comment]
wanna join a funny server im very much expecting no

**Comment by overlisted** [comment]
maybe (perhaps (i am intrigued))

**Comment by SomeoneRand0m101** [comment]
gets ddosed 1 second later aftwe sharing server IP

**Comment by overlisted** [comment]
so true (dm me)
